"""create users table

Revision ID: 7fd2d11944a7
Revises: 
Create Date: 2023-08-10 08:51:03.926893

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "7fd2d11944a7"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sex",
        sa.Column("code", sa.CHAR(length=1), nullable=False),
        sa.Column("name", sa.String(length=10), nullable=False),
        sa.PrimaryKeyConstraint("code"),
    )
    op.create_table(
        "users",
        sa.Column(
            "id",
            mysql.BIGINT(unsigned=True),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("email", sa.String(length=100), nullable=True),
        sa.Column("phone", sa.String(length=15), nullable=True),
        sa.Column("hashed_password", sa.String(length=100), nullable=False),
        sa.Column(
            "is_email_verified",
            sa.Boolean(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "is_phone_verified",
            sa.Boolean(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "is_google_verified",
            sa.Boolean(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "is_facebook_verified",
            sa.Boolean(),
            server_default="0",
            nullable=False,
        ),
        sa.Column(
            "is_active", sa.Boolean(), server_default="1", nullable=False
        ),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.Column("sex_code", sa.CHAR(length=1), nullable=True),
        sa.Column("birthday", sa.Date(), nullable=True),
        sa.Column("facebook_id", sa.String(length=100), nullable=True),
        sa.Column(
            "facebook_access_token", sa.String(length=255), nullable=True
        ),
        sa.Column("facebook_username", sa.String(length=50), nullable=True),
        sa.Column("google_id", sa.String(length=100), nullable=True),
        sa.Column("google_access_token", sa.String(length=255), nullable=True),
        sa.Column("google_username", sa.String(length=50), nullable=True),
        sa.Column("created_at", mysql.BIGINT(), nullable=True),
        sa.Column("updated_at", mysql.BIGINT(), nullable=True),
        sa.Column("deleted_at", mysql.BIGINT(), nullable=True),
        sa.ForeignKeyConstraint(
            ["sex_code"],
            ["sex.code"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("hashed_password"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_phone"), "users", ["phone"], unique=True)
    op.create_index(
        op.f("ix_users_facebook"), "users", ["facebook_id"], unique=True
    )
    op.create_index(
        op.f("ix_users_google"), "users", ["google_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_phone"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_index(op.f("ix_users_facebook"), table_name="users")
    op.drop_index(op.f("ix_users_google"), table_name="users")

    op.drop_table("users")
    op.drop_table("sex")
    # ### end Alembic commands ###
