"""empty message

Revision ID: 3b3dc5561c5f
Revises: 7fd2d11944a7
Create Date: 2023-08-12 11:59:06.247843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = "3b3dc5561c5f"
down_revision: Union[str, None] = "7fd2d11944a7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("user_code", sa.String(length=36), nullable=True)
    )
    op.create_index(
        op.f("ix_users_user_code"), "users", ["user_code"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_user_code"), table_name="users")
    op.drop_column("users", "user_code")
    # ### end Alembic commands ###
